name: "build-from-config-files-update-dispatch"
env:
  DOCKERHUB_IMAGE_PREFIX: abesesr/documentation
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ update_config_files ]

jobs:
  # traitement des trois branches
  build-from-config-files-update-dispatch:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'update_config_files'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "main", "test", "develop" ]
      fail-fast: false
    steps:
      - name: "Build: checkout source code (${{ matrix.branch }})"
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          submodules: recursive

      - name: "Build: update submodules"
        run: |
          git submodule sync
          git submodule update --init --recursive --remote
          cd config-module
          git checkout main
          git pull origin main
          cd ..

      - name: "Build: build docker image"
        run: |
          docker build --build-arg DOCUMENTATION_API_PUBLISH_SCENARI_API_FOLDER=${{ matrix.branch }} . -t localimage:latest

      - name: "Push: prepare version from git tags/branches"
        id: docker_tag_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE_PREFIX }}
          tags: |
            type=raw,value=${{ matrix.branch }},enable=${{ matrix.branch != '' }}

      - name: "Push: login to DockerHub"
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: "Push: push docker image"
        run: |
          DOCKER_TAGS="${{ steps.docker_tag_meta.outputs.tags }}"
          for DOCKER_TAG in $DOCKER_TAGS; do
            docker build --build-arg DOCUMENTATION_API_PUBLISH_SCENARI_API_FOLDER=${{ matrix.branch }} . -t ${DOCKER_TAG}-documentation-api-publish
            docker push ${DOCKER_TAG}-documentation-api-publish
          done
